version: "3"
services:
  data-platform-authenticator-database:
    image : mysql:latest
    container_name: data-platform-authenticator-database
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./config.cnf:/etc/mysql/conf.d/config.cnf
      #      - ./init-dump:/docker-entrypoint-initdb.d
      - ./:/app/src
      - ../data-platform-authenticator-mysql-kube/data-platform-authenticator-sql-business-user-data.sql:/app/src/data-platform-authenticator-sql-business-user-data.sql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    working_dir: /app/src
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXXXXX
      MYSQL_DATABASE: DataPlatformAuthenticatorMySQLKube
      MYSQL_USER: XXXXXXXXX
      MYSQL_PASSWORD: XXXXXXXXX
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      application:
        ipv4_address: XXXXXXXXXXXX

  data-platform-authenticator-application:
    build:
      context: .
      dockerfile: ./Dockerfile_Hotreload
    container_name: data-platform-authenticator-application
    ports:
      - "50500:50500"
    volumes:
      - .:/opt/app
    environment:
      DATA_PLATFORM_AUTHENTICATOR_MYSQL_KUBE: XXXXXXXXX
      MYSQL_PORT: 3306
      DATA_BASE_NAME: DataPlatformAuthenticatorSQL
      TABLE_NAME: data_platform_authenticator_business_user_data
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MAX_IDLE_CON: 5
      MAX_LIFE_TIME: 24
      MAX_OPEN_CON: 10
      PRIVATE_KEY: "${PRIVATE_KEY}"
      PUBLIC_KEY: "${PUBLIC_KEY}"
      AUTHENTICATOR_PORT: ${AUTHENTICATOR_PORT}
      SHUT_DOWN_WAIT_TIME: 1
      EXP: 24
    tty: true
    networks:
      application:
        ipv4_address: XXXXXXXXXXXX

networks:
  application:
    ipam:
      driver: default
      config:
        - subnet: XXXXXXXXXXXX/16
